name: Deploy to Staging

on:
  push:
    branches: main # Trigger the workflow on a push to the main branch

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  artifactName: buildArtifact # This must match the artifact name in the build-and-test workflow
  projectName: "ci-cd-task" # Manually specify the project name

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml
    secrets: inherit # Pass secrets to the build workflow, if necessary

  deploy-to-staging:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Update to v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Download artifact
        uses: actions/download-artifact@v4 # Update to v4
        with:
          name: ${{ env.artifactName }}
          path: ./buildArtifact

      - name: List build artifact directory
        run: ls -la ./buildArtifact

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

