name: Deploy to Production

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

env:
  artifactName: buildArtifact # This must match the artifact name in the build-and-test workflow

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml
    secrets: inherit # Pass secrets to the build workflow, if necessary

  deploy-to-production:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: production # Used for environment-specific variables, secrets, and approvals
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.artifactName }}
          path: ./buildArtifact

      - name: Deploy to Vercel (Production)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --scope your-vercel-scope --confirm --cwd ./buildArtifact
