name: Deploy to Staging

on:
  push:
    branches: main # Trigger the workflow on a push to the main branch

env:
  artifactName: buildArtifact # This must match the artifact name in the build-and-test workflow

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml
    secrets: inherit # Pass secrets to the build workflow, if necessary

  deploy-to-staging:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the new repository
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.artifactName }}
          path: ./buildArtifact

      - name: List build artifact directory
        run: ls -la ./buildArtifact

      - name: Deploy to Vercel (Staging)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: npx vercel --token ${{ secrets.VERCEL_TOKEN }} --yes --cwd ./buildArtifact --debug

